### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dventurino** [facundoolano/aso#25]
Hello,
a while ago I made a script  following the README of this repo and it has been working fine for months...now I get a bunch of UnhandledPromiseRejectionWarning and the script does not complete its execution.

`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined`

The script only contains instructions as explained in the README file:

`aso.visibility(packageName).then(console.log);`

I'm on the latest 1.1.1 version, Node v.11..8.0

Any ideas?

**Comment by dventurino** [comment]
`node:23260) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/Users/Daniele/Desktop/test/node_modules/google-play-scraper/lib/app.js:181:51)
    at R.map (/Users/Daniele/Desktop/test/node_modules/google-play-scraper/lib/app.js:175:17)
    at XWrap.f (/Users/Daniele/Desktop/test/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/Users/Daniele/Desktop/test/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/Daniele/Desktop/test/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/Users/Daniele/Desktop/test/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/Users/Daniele/Desktop/test/node_modules/ramda/dist/ramda.js:5954:20)
    at /Users/Daniele/Desktop/test/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/Users/Daniele/Desktop/test/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/Users/Daniele/Desktop/test/node_modules/google-play-scraper/lib/app.js:169:12)`

**Comment by b-reynolds** [comment]
I suspect this is related to this issue

https://github.com/facundoolano/google-play-scraper/issues/289#issue-404146013

It looks like a couple of people are working on a fix for it now.

**Comment by facundoolano** [comment]
should be fixed by a npm install
