### ISSUE TITLE
Score command not working correctly

### ISSUE THREAD

**Issue by hexdump2002** [facundoolano/aso#27]
Score comamnd was working correctly but suddenly it started to fail, but not always :). I have been checking it with simple requests and sometimes it returns the correct data from difficulty and traffic and others doesn't. Competitors fields appears to be 0 when failing leading to a lot of NAN values because of zero division.

Is there something we could do?

Cheers.

**Comment by facundoolano** [comment]
This is likely related to underlying issues with google play scraper (search and similar methods broken at the moment) 

https://github.com/facundoolano/google-play-scraper/issues/305

**Comment by adampound** [comment]
difficulty is always null for me.  Is there a work around?  Traffic is working.  The app list doesnt contain the minInstalls field when calculating difficulty.

**Comment by angel1st** [comment]
@facundoolano - I believe I have experienced the same issue. 
After installing the module, here is my index.js file content:

```
const aso = require('aso')('gplay');

aso.scores('bmi calculator').then(console.log)
```

and here is the output - every time:

> (node:8240) UnhandledPromiseRejectionWarning: Error: App not found (404)
    at /home/user/public/aso_tool/node_modules/google-play-scraper/lib/utils/request.js:44:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any chances to have it fixed?

**Comment by PatrickRNG** [comment]
Score not working on Itunes as well.. any fixes or idea that i can fix it?

`TypeError: Cannot read property 'href' of undefined
at Array.map
at processTicksAndRejections (internal/process/task_queues.js:94:5)
at async Promise.all (index 3)
at async Promise.all (index 0)
at async Promise.all (index 1)
at async getKeywordScore`
