### ISSUE TITLE
Stopped working last week

### ISSUE THREAD

**Issue by michaelforrest** [facundoolano/aso#39]
This started giving me an error last week - I don't know if Apple changed something?

```
Error: Error: Invalid category 6025
    at validate (/Users/mf/code/coda/weekly-report/node_modules/app-store-scraper/lib/list.js:63:11)
    at /Users/mf/code/coda/weekly-report/node_modules/app-store-scraper/lib/list.js:82:5
    at new Promise (<anonymous>)
    at Object.list (/Users/mf/code/coda/weekly-report/node_modules/app-store-scraper/lib/list.js:80:10)
    at Object.list (/Users/mf/code/coda/weekly-report/node_modules/memoizee/lib/configure-map.js:42:41)
    at /Users/mf/code/coda/weekly-report/node_modules/aso/lib/stores/itunes.js:28:26
    at Array.map (<anonymous>)
    at getRankedApps (/Users/mf/code/coda/weekly-report/node_modules/aso/lib/scores/traffic.js:35:32)
    at /Users/mf/code/coda/weekly-report/node_modules/aso/lib/scores/traffic.js:80:7
    at runMicrotasks (<anonymous>)
error Command failed with exit code 1.
```
I'll also post this on `app-store-scraper` in case it's on their end.

**Comment by michaelforrest** [comment]
Hi @facundoolano - is this project still maintained?
